# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Overview'
  link: '/overview'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Advanced'
  link: '/advanced'
- label: 'Tutorial'
  link: '/tutorial'
- label: 'BotAction'
  items:
    - label: 'Assembly Lines'
      link: '/botaction/assembly-lines'
    - label: 'Console'
      link: '/botaction/console'
    - label: 'Cookies'
      link: '/botaction/cookies'
    - label: 'Errors'
      link: '/botaction/errors'
    - label: 'Files'
      link: '/botaction/files'
    - label: 'IndexedDB'
      link: '/botaction/indexed-db'
    - label: 'Inject'
      link: '/botaction/inject'
    - label: 'Input'
      link: '/botaction/input'
    - label: 'Local Storage'
      link: '/botaction/local-storage'
    - label: 'Navigation'
      link: '/botaction/navigation'
    - label: 'Pipe'
      link: '/botaction/pipe'
    - label: 'Utilities'
      link: '/botaction/utilities'
- label: 'Helper'
  items:
    - label: 'Console'
      link: '/helper/console'
    - label: 'Files'
      link: '/helper/files'
    - label: 'Navigation'
      link: '/helper/navigation'
    - label: 'Pipe'
      link: '/helper/pipe'
    