# Sidebar navigation

- label: 'Getting Started'
  items:
  - label: 'Introduction'
    link: '/'
  - label: 'Overview'
    link: '/overview'
  - label: 'Install'
    link: '/install'
  - label: 'Examples'
    link: '/examples'
  - label: 'Tutorial'
    link: '/tutorial'

- label: 'Topics'
  items:
    - label: 'Conditionals'
      link: '/topic/conditionals'
    - label: 'Loops'
      link: '/topic/loops'
    - label: 'Error Handling'
      link: '/topic/error-handling'
    - label: 'Aborting'
      link: '/topic/aborting'
    - label: 'Piping'
      link: '/topic/piping'
    - label: 'Injects'
      link: '/topic/injects'
    - label: 'Concurrency'
      link: '/topic/concurrency'

- label: 'Auxiliary'
  items:
    - label: 'Instagram'
      link: '/sites/instagram'
    - label: 'LinkedIn'
      link: '/sites/linkedin'
    - label: 'Twitter'
      link: '/sites/twitter'

- label: 'Core'
  items:
    - label: 'Abort'
      link: '/api/abort'
    - label: 'Assembly Lines'
      link: '/api/assembly-lines'
    - label: 'Branching'
      link: '/api/branching'
    - label: 'Console'
      link: '/api/console'
    - label: 'Cookies'
      link: '/api/cookies'
    - label: 'Errors'
      link: '/api/errors'
    - label: 'Files'
      link: '/api/files'
    - label: 'IndexedDB'
      link: '/api/indexed-db'
    - label: 'Inject'
      link: '/api/inject'
    - label: 'Input'
      link: '/api/input'
    - label: 'Local Storage'
      link: '/api/local-storage'
    - label: 'Loops'
      link: '/api/loops'
    - label: 'Navigation'
      link: '/api/navigation'
    - label: 'Pipe'
      link: '/api/pipe'
    - label: 'Random'
      link: '/api/random'
    - label: 'Scrapers'
      link: '/api/scrapers'
    - label: 'Time'
      link: '/api/time'

- label: 'Dev'
  items:
    - label: 'Roadmap'
      link: /roadmap
    - label: 'Contributors'
      link: /contributors