# Sidebar navigation

- label: 'Getting Started'
  items:
  - label: 'Introduction'
    link: '/'
  - label: 'Overview'
    link: '/overview'
  - label: 'Playground'
    link: '/playground'
  - label: 'Examples'
    link: '/examples'
  - label: 'Install'
    link: '/install'

- label: 'Sites'
  items:
    - label: 'Instagram'
      link: '/sites/instagram'
    - label: 'LinkedIn'
      link: '/sites/linkedin'

- label: 'Advanced'
  items:
    - label: 'Aborting'
      link: '/advanced/aborting'
    - label: 'Piping'
      link: '/advanced/piping'
    - label: 'Injects'
      link: '/advanced/injects'
    - label: 'Conditionals'
      link: '/advanced/conditionals'
    - label: 'Loops'
      link: '/advanced/loops'
    - label: 'Error Handling'
      link: '/advanced/error-handling'
    - label: 'Concurrency'
      link: '/advanced/concurrency'
    - label: 'Tutorial'
      link: '/advanced/tutorial'

- label: 'API'
  items:
    - label: 'Abort'
      link: '/api/abort'
    - label: 'Assembly Lines'
      link: '/api/assembly-lines'
    - label: 'Console'
      link: '/api/console'
    - label: 'Cookies'
      link: '/api/cookies'
    - label: 'Errors'
      link: '/api/errors'
    - label: 'Files'
      link: '/api/files'
    - label: 'IndexedDB'
      link: '/api/indexed-db'
    - label: 'Inject'
      link: '/api/inject'
    - label: 'Input'
      link: '/api/input'
    - label: 'Local Storage'
      link: '/api/local-storage'
    - label: 'Navigation'
      link: '/api/navigation'
    - label: 'Pipe'
      link: '/api/pipe'
    - label: 'Scrapers'
      link: '/api/scrapers'
    - label: 'Utilities'
      link: '/api/utilities'
    
- label: 'Dev'
  items:
    - label: 'Roadmap'
      link: /roadmap
    - label: 'Contributors'
      link: /contributors